/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ddb8ff",
        "surface-container-low": "var(--surface-container-low)",
        "tertiary-fixed-dim": "#c5c6cf",
        "background": "var(--background)",
        "on-tertiary-fixed": "#191b22",
        "secondary-fixed": "#ffd9e3",
        "on-error": "#690005",
        "on-surface-variant": "var(--on-surface-variant)",
        "secondary-fixed-dim": "#ffb0cb",
        "error": "#ffb4ab",
        "tertiary-fixed": "#e2e2ec",
        "primary": "var(--primary)",
        "primary-fixed": "#f0dbff",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "tertiary-container": "#696a73",
        "surface-container-high": "var(--surface-container-high)",
        "primary-container": "var(--primary-container)",
        "on-secondary": "var(--on-secondary)",
        "secondary-light": "var(--secondary-light)",
        "outline-variant": "var(--outline-variant)",
        "on-primary-container": "#f6e6ff",
        "outline": "var(--outline)",
        "primary-fixed-dim": "var(--primary)",
        "secondary-container": "var(--secondary-container)",
        "inverse-on-surface": "#2f3035",
        "on-background": "var(--on-background)",
        "on-surface": "var(--on-surface)",
        "on-tertiary-fixed-variant": "#45464e",
        "surface": "var(--surface)",
        "on-tertiary": "#2e3038",
        "surface-dim": "#121317",
        "secondary": "var(--secondary)",
        "on-primary": "var(--on-primary)",
        "primary-light": "var(--primary-light)",
        "surface-variant": "var(--surface-variant)",
        "tertiary": "#c5c6cf",
        "on-secondary-fixed-variant": "#8d004f",
        "inverse-surface": "#e3e2e7",
        "on-secondary-fixed": "#3e0020",
        "on-secondary-container": "#ffb5ce",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-bright": "#38393d",
        "inverse-primary": "#861fdd",
        "surface-container": "var(--surface-container)",
        "on-tertiary-container": "#ebebf5",
        "on-primary-fixed-variant": "#6800b4",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-primary-fixed": "#2c0051"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter-sm": "16px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "gutter-md": "24px",
        "unit": "4px"
      },
      fontFamily: {
        "display-lg": ["Outfit", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
