/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ddb8ff",
        "surface-container-low": "#1a1b20",
        "tertiary-fixed-dim": "#c5c6cf",
        "background": "#121317",
        "on-tertiary-fixed": "#191b22",
        "secondary-fixed": "#ffd9e3",
        "on-error": "#690005",
        "on-surface-variant": "#cfc2d7",
        "secondary-fixed-dim": "#ffb0cb",
        "error": "#ffb4ab",
        "tertiary-fixed": "#e2e2ec",
        "primary": "#ddb8ff",
        "primary-fixed": "#f0dbff",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "tertiary-container": "#696a73",
        "surface-container-high": "#292a2e",
        "primary-container": "#9333ea",
        "on-secondary": "#640036",
        "outline-variant": "#4d4354",
        "on-primary-container": "#f6e6ff",
        "outline": "#988ca0",
        "primary-fixed-dim": "#ddb8ff",
        "secondary-container": "#a7005e",
        "inverse-on-surface": "#2f3035",
        "on-background": "#e3e2e7",
        "on-surface": "#e3e2e7",
        "on-tertiary-fixed-variant": "#45464e",
        "surface": "#121317",
        "on-tertiary": "#2e3038",
        "surface-dim": "#121317",
        "secondary": "#ffb0cb",
        "on-primary": "#490080",
        "surface-variant": "#343439",
        "tertiary": "#c5c6cf",
        "on-secondary-fixed-variant": "#8d004f",
        "inverse-surface": "#e3e2e7",
        "on-secondary-fixed": "#3e0020",
        "on-secondary-container": "#ffb5ce",
        "surface-container-highest": "#343439",
        "surface-bright": "#38393d",
        "inverse-primary": "#861fdd",
        "surface-container": "#1f1f24",
        "on-tertiary-container": "#ebebf5",
        "on-primary-fixed-variant": "#6800b4",
        "surface-container-lowest": "#0d0e12",
        "on-primary-fixed": "#2c0051"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter-sm": "16px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "gutter-md": "24px",
        "unit": "4px"
      },
      fontFamily: {
        "display-lg": ["Outfit", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
